default:
	python ./tools/log.py

unzip_aab:
	python ./tools/unzip_aab.py

auto_backup:
	python ./tools/auto_backup.py

auto_backup_online:
	python ./tools/auto_backup.py
	python ./tools/auto_backup_online.py

auto_backup_fix_update:
	python ./tools/auto_backup_fix_update.py